<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="balance_bot">


  <!-- Load in parameters from the YAML file -->
  <xacro:property name="props" value="${load_yaml('$(find dynamics)/config/robot_params.yaml')}"/>

  <xacro:property name="wheel_radius" value="${props['wheel_radius']}"/>
  <xacro:property name="wheel_radius" value="${props['body_wheel_base']}"/>
  <xacro:property name="body_width" value="${props['body_width']}"/>
  <xacro:property name="body_height" value="${props['body_height']}"/>
  <xacro:property name="body_thickness" value="${props['body_thickness']}"/>

  <!-- Macro to load a part with a mesh -->
  <xacro:macro name="link_mesh" params="name origin_xyz origin_rpy meshfile meshscale">
    <link name="${name}">
      <visual>
        <origin rpy="${origin_rpy}" xyz="${origin_xyz}" />
        <geometry>
          <mesh filename="${meshfile}" scale="${meshscale}"/>
        </geometry>
        <material name="red"/>
      </visual>
    </link>
  </xacro:macro>

  <!-- Macro to create wheels -->
  <!-- <xacro:macro name="wheel_temp" params="wheel_side offset">
    <link name="wheel_${wheel_side}">
      <visual>
        <origin rpy="${pi/2} 0 0" xyz="0 ${offset * (wheel_width/2)} 0"/>
      </visual>
    </link>

    <joint name="${wheel_side}_wheel_axel" type="continuous">
      <origin xyz="${base_shift-.25*chassis_length} ${offset * (chassis_width/2)} ${wheel_radius}" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="wheel_${wheel_side}" />
      <axis xyz="0 1 0"/>
    </joint>
  </xacro:macro> -->

  <!-- Macro to create casters -->
  <!-- <xacro:macro name="caster_temp" params="caster_side offset">
    <link name="caster_${caster_side}">
      <visual>
        <geometry>
            <sphere radius="${castor_radius}" />
        </geometry>
        <material name="white_mat">
          <color rgba=".9 .9 .9 .95" />
        </material>
        <origin rpy="0 0 0" xyz="0 0 0"/>
      </visual>
    </link>

    <joint name="${caster_side}_castor_joint" type="fixed">
      <origin xyz="${base_shift + (chassis_length/2 - castor_radius)} 0 ${castor_radius}" rpy="0 0 0" />
      <parent link="base_link"/>
      <child link="caster_${caster_side}" />
    </joint>
  </xacro:macro> -->

  <!-- The base link of the robot center between the two wheels directly below the COM of the body -->
  <link name="base_link" >
    <visual>
      <geometry>
        <sphere radius=".05" />
      </geometry>
      <material name="invisible">
        <color rgba="0 0 0 1" />
      </material>
      <origin rpy="0 0 0" xyz="0 0 ${wheel_radius}"/>
    </visual>
  </link>

  <!-- This is a body link used to represent the body of the robot. All STLs are fixed to it-->
  <link name="moving_link">
    <visual>
      <geometry>
        <box size="${body_thickness} ${body_width} ${body_height}" />
      </geometry>
      <material name="red"/>
      <origin xyz="0 0 ${body_height/2}" rpy="0 0 0"/>
    </visual>
  </link>

  <joint name="body_joint" type="continuous">
    <origin xyz="0 0 ${wheel_radius}" rpy="0 0 0" />
    <parent link="base_link"/>
    <child link="moving_link" />
    <axis xyz="0 1 0"/>
  </joint>

  <xacro:link_mesh name="bottom_plate" origin_xyz="-1 -2 0" origin_rpy="${pi/2} 0 ${pi/2}"
    meshfile="package://visualization/meshes/BottomPlate.STL"
    meshscale="0.0254 0.0254 0.0254"/>

  <joint name="bottom_plate_joint" type="fixed">
    <origin xyz="0 0 0" rpy="0 0 0" />
    <parent link="moving_link"/>
    <child link="bottom_plate" />
  </joint>


  <!-- Wheel Creation -->

  <!-- Caster Creation -->

</robot>
