frequency: 200 # Hz, sets computation rate

kp_ang: 0.4 # proportional gain for body angle, must be positive
ki_ang: 0.045 # integral gain for body angle, must be positive
kd_ang: 0.035 # derivative gain for body angle, must be positive

kp_x: 0.05 # proportional gain for body x position, must be positive
ki_x: 0 #0.005 # integral gain for body x position, must be positive
kd_x: 0.3 #0.04 # derivative gain for body x position, must be positive
